// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA-ZrfwyzvOGZ5ZUWTyR_HSrugSonucN8Y',
    appId: '1:666556841944:web:5cf4cafb8c08880b45fcad',
    messagingSenderId: '666556841944',
    projectId: 'ozgurdoviz',
    authDomain: 'ozgurdoviz.firebaseapp.com',
    storageBucket: 'ozgurdoviz.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAB_ayhe6V3tCLMHmTzETb99MPDCDBoB68',
    appId: '1:666556841944:android:6b8e6b92df6b6aad45fcad',
    messagingSenderId: '666556841944',
    projectId: 'ozgurdoviz',
    databaseURL: 'https://ozgurdoviz-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'ozgurdoviz.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC89-8uBgVE_bybVCdvgpmDs1Z1gyvvog4',
    appId: '1:666556841944:ios:bbe8ec1b5166bdb745fcad',
    messagingSenderId: '666556841944',
    projectId: 'ozgurdoviz',
    databaseURL: 'https://ozgurdoviz-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'ozgurdoviz.appspot.com',
    iosBundleId: 'com.example.untitled',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC89-8uBgVE_bybVCdvgpmDs1Z1gyvvog4',
    appId: '1:666556841944:ios:bbe8ec1b5166bdb745fcad',
    messagingSenderId: '666556841944',
    projectId: 'ozgurdoviz',
    storageBucket: 'ozgurdoviz.appspot.com',
    iosBundleId: 'com.example.untitled',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA-ZrfwyzvOGZ5ZUWTyR_HSrugSonucN8Y',
    appId: '1:666556841944:web:05035073d016ecee45fcad',
    messagingSenderId: '666556841944',
    projectId: 'ozgurdoviz',
    authDomain: 'ozgurdoviz.firebaseapp.com',
    storageBucket: 'ozgurdoviz.appspot.com',
  );
}